name: Download daily reservoir data

on:
  schedule:
    - cron: "0 10 * * *" # run every day at 3 a.m. PST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - name: Install dependencies
      run: pipenv install --skip-lock
    - name: Get data
      run: make reservoirs
    # - name: Run statewide scraper
    #   run: pipenv run jupyter execute reservoirs/download/01-statewide.ipynb
    # - name: Run DWR scraper
    #   run: pipenv run jupyter execute reservoirs/download/02-dwr.ipynb  
    # - name: Run BoR scraper
    #   run: pipenv run jupyter execute reservoirs/download/03-colorado-bor.ipynb
    # - name: Process statewide reservoirs
    #   run: pipenv run jupyter execute reservoirs/process/01-statewide.ipynb
    # - name: Process DWR data
    #   run: pipenv run jupyter execute reservoirs/process/02-dwr.ipynb
    # - name: Process BoR data
    #   run: pipenv run jupyter execute reservoirs/process/03-colorado.ipynb      
    - name: Add and commit 
      uses: EndBug/add-and-commit@v9
      with:
        message: 'Latest reservoir data'
