name: Download daily reservoir data

on:
  schedule:
    - cron: "0 10 * * *" # run every day at 3 a.m. PST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        cache: 'pipenv'

    - id: install-pipenv
      name: Install pipenv
      run: |
        python -m pip install --upgrade --no-cache-dir pip
        python -m pip install --no-cache-dir pipenv
      shell: bash
  
    - id: cache-pipfile
      name: Cache Pipfile
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
      
    - id: sync-pipfile
      name: Sync Pipfile
      run: pipenv sync
      shell: bash
    
    - name: Run statewide scraper
      run: pipenv run jupyter execute downloaders/reservoirs/reservoirs-statewide.ipynb
    - name: Run DWR scraper
      run: pipenv run jupyter execute downloaders/reservoirs/reservoirs-dwr.ipynb  
    - name: Run BoR scraper
      run: pipenv run jupyter execute downloaders/reservoirs/reservoirs-colorado-bor.ipynb
    - name: Process statewide reservoirs
      run: pipenv run jupyter execute processors/reservoirs/reservoirs-statewide.ipynb
    - name: Process DWR data
      run: pipenv run jupyter execute processors/reservoirs/reservoirs-dwr.ipynb
    - name: Process BoR data
      run: pipenv run jupyter execute processors/reservoirs/reservoirs-colorado.ipynb      
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest reservoir data"
    - name: Push
      run: git push
