name: Download daily reservoir data

on:
  schedule:
    - cron: "0 10 * * *" # run every day at 3 a.m. PST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install
    - name: Install requirements
      run: pipenv install -r requirements.txt    
    - name: Run statewide scraper
      run: pipenv run jupyter execute downloaders/reservoirs-statewide.ipynb
    - name: Run DWR scraper
      run: pipenv run jupyter execute downloaders/reservoirs-dwr.ipynb  
    - name: Process statewide reservoirs
      run: pipenv run jupyter execute processors/reservoirs-statewide.ipynb
    - name: Process DWR data
      run: pipenv run jupyter execute processors/reservoirs-dwr.ipynb
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest water conservation data"
    - name: Push
      run: git push
