name: Download & process urban water data

on:
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install dependencies
        run: pipenv install
      - name: Download and process data
        run: make urbanwateruse
      - name: Add and commit 
        uses: EndBug/add-and-commit@v8
        with:
          message: 'New files data added'
