name: Download & process urban water data

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install
    - name: Install requirements
      run: pipenv install -r requirements.txt    
    - name: Run scraper
      run: pipenv run jupyter execute downloaders/uw-monthly-reports.ipynb
    - name: Parse monthly reports
      run: pipenv run jupyter execute processors/1-parse-uw-monthly-reports.ipynb      
    - name: R-GPCD
      run: pipenv run jupyter execute processors/2-r-gpcd.ipynb
#     - name: Calculate monthly percent changes
#       run: pipenv run jupyter execute processors/3-conservation-progress.ipynb
#     - name: Process drought response actions data
#       run: pipenv run jupyter execute processors/4-drought-response.ipynb      
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest water conservation data"
    - name: Push
      run: git push
