name: Download & process urban water data

on:
  schedule:
  - cron: 35 7 * * 5 # every Friday around 7:35 p.m. Pacific
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install dependencies
        run: pipenv install    
      # - name: Run scraper
      #   # if: steps.check_file.outputs.file_change == 'true'
      #   run: pipenv run python urban-water-use/scrape.py
      # - name: Process data
      #   # if: steps.check_file.outputs.file_change == 'true'
      #   run: pipenv run jupyter execute urban-water-use/r-gpcd.ipynb
      - name: Get urban water use data
        run: make urbanwaterusedata
      - name: Add and commit 
        uses: EndBug/add-and-commit@v9
        with:
          message: 'New files data added'
