name: Download & process urban water data

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install
    - name: Install requirements
      run: pipenv install -r requirements.txt
    # - name: Process data
      # run: make urban-water-use
    - name: Run scraper
      run: python urban-water-use/scrape.py
    - name: Process
      run: pipenv run jupyter execute urban-water-use/r-gpcd.ipynb  
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest water conservation data"
    - name: Push
      run: git push
