name: Download daily precipitation data

on:
  schedule:
    - cron: "15 20 * * *" # set to run every day at 12:15 p.m. PST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install dependencies
        run: pipenv install
      - name: Get precip data
        run: make precipitationdata
      # - name: Run total scraper
      #   run: pipenv run jupyter execute precipitation/precipitation.ipynb  
      # - name: Run daily scraper
      #   run: pipenv run jupyter execute precipitation/daily-precipitation.ipynb        
      - name: Add and commit
        id: add_commit
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: Automated
          committer_email: actions@users.noreply.github.com
          message: "Latest precipitation data"
      - name: Push
        run: git push
