name: Download daily precipitation data

on:
  schedule:
    - cron: "15 20 * * *" # set to run every day at 12:15 p.m. PST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pipenv
      run: pipx install pipenv
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pipenv'
    - run: pipenv install
    - name: Install requirements
      run: pipenv install -r requirements.txt    
    - name: Run total scraper
      run: pipenv run jupyter execute precipitation/precipitation.ipynb  
    - name: Run daily scraper
      run: pipenv run jupyter execute precipitation/daily-precipitation.ipynb        
    - name: Add and commit
      id: add_commit
      uses: EndBug/add-and-commit@v8
      with:
        committer_name: Automated
        committer_email: actions@users.noreply.github.com
        message: "Latest precipitation data"
    - name: Push
      run: git push
